[global]
author=["community"]

[parse]
sourcefile=[ "d_kbash.cpp" ]

[buttons]
names=[
    { names="Punch1,Punch2,Punch3" }
]

[dipsw]
delete=[{names=["Unused","Unknown"]}]

[ROM]
regions = [
    { name="maincpu", width=16, reverse=true, no_offset=true },
    { name="audiocpu", start="JTFRAME_BA1_START" },
    { name="gfx1", start="JTFRAME_BA2_START", width=16, no_offset=true },
    { name="gfx2", start="JTFRAME_BA3_START", width=16, no_offset=true }
]

order = [
    "maincpu", "gfx1", "gfx2", "audiocpu"
]
