[global]
author=["community"]

[parse]
sourcefile=[ "twincobr.cpp" ]

[buttons]
names=[
    { names="Fire 1,Fire 2" }
]

[dipsw]
delete=[{names=["Unused","Unknown"]}]

[ROM]
regions = [
    { name="maincpu", width=16, reverse=true, no_offset=true },
    { name="audiocpu", start="0x80000" },
    { name="gfx1", start="0x100000" },
    { name="gfx2", start="0x200000" },
    { name="gfx3", start="0x300000" },
    { name="gfx4", start="0x400000" }
]

order = [
    "maincpu", "audiocpu", "gfx1", "gfx2", "gfx3", "gfx4"
]
