name: Build jtbubl

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths:
      - 'cores/bubl/**'
      - '.github/workflows/build-bubl.yaml'

jobs:
  compile_bubl:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Clone needed submodules
        run: |
          rm -rf modules/fx68k modules/jt12 modules/jtopl modules/jt51 modules/jt5205 modules/jtkcpu modules/jtframe
          git clone --depth 1 https://github.com/jtfpga/fx68k modules/fx68k
          git clone --depth 1 --recursive https://github.com/jotego/jt12 modules/jt12
          git clone --depth 1 --recursive https://github.com/jotego/jtopl modules/jtopl
          git clone --depth 1 https://github.com/jotego/jt51 modules/jt51
          git clone --depth 1 https://github.com/jotego/jt5205 modules/jt5205
          git clone --depth 1 https://github.com/jotego/jtkcpu modules/jtkcpu
          git clone --depth 1 https://github.com/jotego/jtframe modules/jtframe
          ls modules/jt12/cfg/jt03.yaml modules/jt12/jt49/hdl/jt49.v modules/jtopl/cfg/jt26.yaml
      - id: compile
        run: |
          docker run --network host -v $(pwd):/jtcores jotego/jtcore20 /jtcores/modules/jtframe/devops/xjtcore.sh bubl mister
      - uses: actions/upload-artifact@v4
        with:
          name: jtbubl-rebuilt
          path: release
          retention-days: 7
